#!/bin/bash
# Check if Escape has been mapped to Caps_Lock

bool=$(xmodmap -pm | grep lock | grep -c "\(0x9\)")
if [ $bool -eq 0 ]; then
    source /home/daniel/.zprofile
    echo "Escape key re-mapped to Caps-Lock"
fi

