#!/bin/bash

## This program takes one or two keyword as input, and searchs
## for a music files that contains the keywords in either order.
## All audio file types are checked for.

trap die SIGINT # control C

die()
{
  echo -e "\n*** Quiting Play Program ***\n"
}

build_list()
{
    list1=$(find /media/Music -type f -iname "$1.mp3")
    list2=$(find /media/Music -type f -iname "$1.flac")
    list3=$(find /media/Music -type f -iname "$1.wma")
    list4=$(find /media/Music -type f -iname "$1.wav")
    list5=$(find /media/Music -type f -iname "$1.mp4")
  
    echo "$list1$list2$list3$list4$list5"
}

main()
{
  echo -e "\n  --Press CR to skip a track and Shift Control C to quit-- \n"

  string="*$1*$2*"

  list=$(build_list "${string}")
  echo $list
  if [[ "${#list}" -lt 1 ]]; then
    string="*$2*$1*"
    echo -e "reversing order\n"
    list=$(build_list "${string}")
    if [[ "${#list}" -lt 1 ]]; then
      echo -e "\n----Nothing Found----\n"
      exit 1
    fi 
  fi

  echo "$list"

  for track in "${list[@]}"; do
    name=$(basename "${track}")
    echo -e "\nTRACK: $name \n"
    mplayer -slave -really-quiet -af volnorm 2 ${track} 2>/dev/null
  done 

  exit 0
}


main "$@"